---
title: "Data Manipulation with `dplyr`"
author: "Jiajun Tao"
date: "2022-09-22"
output: github_document
---

Once you've imported data, you're going to need to do some cleaning up.

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```
```{r}
library(tidyverse)

options(tibble.print_min = 3)

litters_data = read_csv("./data_import_examples/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data_import_examples/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```


### `select`

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

```{r}
select(litters_data, group:gd_of_birth)
```

```{r}
select(litters_data, -pups_survive, -group)
```
```{r}
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r}
rename(litters_data, GROUP = group, LITTER_NumBer = litter_number)
```

```{r}
select(litters_data, starts_with("gd"))
select(litters_data, ends_with("weight"))
```
```{r}
select(litters_data, litter_number, pups_survive, everything())
```

* `gd_of birth == 20`
* `pups_born_alive >= 2`
* `!(pups_survive == 4)`
* `group %in% c("Con7", "Con8")`
* `group == "Con7" & gd_of_birth == 20`

```{r}
filter(litters_data, gd_of_birth == 20)
filter(litters_data, group == "Con7" & gd_of_birth == 20)
```
```{r}
mutate(litters_data,
       wt_gain = gd18_weight - gd0_weight,
       group = str_to_lower(group),
       #wt_gain_kg = wt_gain * 2.2
)


```

```{r}
head(arrange(litters_data, desc(group), pups_born_alive), 10)
```

using pipe
```{r}
litters_data = 
  read_csv("./data_import_examples/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)
  
litters_data
```

p
